### ISSUE TITLE
A note on branches

### ISSUE THREAD

**Issue by martoio** [liuyi9509/Codecademy-SQL-intensive#10]
I noticed you were using different branches to upload different things in the same repo (you have some older SQL things and now the newer HTML project). I would suggest you keep things separate in separate repositories. This will make it easy to keep project reviews separate for the projects, and it also makes things easier in terms of working with Git.

**Comment by liuyi9509** [comment]
Good idea. I was thinking about that... Thank you.

**Comment by liuyi9509** [comment]
This issue was moved to liuyi9509/codecademy-build-websites-from-scratch-#1
