### ISSUE TITLE
HTML Special characters

### ISSUE THREAD

**Issue by martoio** [liuyi9509/Codecademy-SQL-intensive#3]
Check out this article that explains why you need to care about using special characters in HTML: http://text-symbols.com/html/encode/
The ampersand should be written as:
``&amp;``

https://github.com/liuyi9509/Codecademy-SQL-intensive/blob/3fd7c7abc0d022b1c41e79cf61432a920a3f64b8/index.html#L5

**Comment by liuyi9509** [comment]
This issue was moved to liuyi9509/codecademy-build-websites-from-scratch-#9
