### ISSUE TITLE
Inline styles

### ISSUE THREAD

**Issue by martoio** [liuyi9509/Codecademy-SQL-intensive#5]
Try to avoid inline styles. They are really hard to manage and they end up causing more issues later on. Just apply a class and attach the styles to the class.

https://github.com/liuyi9509/Codecademy-SQL-intensive/blob/3fd7c7abc0d022b1c41e79cf61432a920a3f64b8/index.html#L16

**Comment by liuyi9509** [comment]
This issue was moved to liuyi9509/codecademy-build-websites-from-scratch-#7
