### ISSUE TITLE
Font-family

### ISSUE THREAD

**Issue by martoio** [liuyi9509/Codecademy-SQL-intensive#7]
You can put the ``font-family`` on the ``html`` or ``body`` elements, that way you don't have to constantly specify the font for all the elements:

https://github.com/liuyi9509/Codecademy-SQL-intensive/blob/3fd7c7abc0d022b1c41e79cf61432a920a3f64b8/style.css#L12

**Comment by liuyi9509** [comment]
This issue was moved to liuyi9509/codecademy-build-websites-from-scratch-#5
